version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: nest_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5435:5432"   # Host:Container (lo importante es 5435 en el host)
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
